name: Flutter CI/CD

on:
  push:
    branches: [ dev-vikas ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test || true

      - name: Build APK
        run: flutter build apk --release

      - name: Build Web
        run: flutter build web