import '../../../utils/constant.dart';

enum AppIconsPaths {
  icCross('${AppConstants.iconDefault}ic_cross.svg'),
  icMenu('${AppConstants.iconDefault}ic_menu.svg'),
  icNotification('${AppConstants.iconDefault}ic_notification.svg'),
  icLeaderboard('${AppConstants.iconDefault}ic_leaderboard.svg'),
  icMyProfile('${AppConstants.iconDefault}ic_my_profile.svg'),
  icMyBooking('${AppConstants.iconDefault}ic_mybooking.svg'),
  icTeeTime('${AppConstants.iconDefault}ic_tee_time.svg'),
  icSearch('${AppConstants.iconDefault}ic_search.svg'),
  icBackArrow('${AppConstants.iconDefault}ic_back_arrow.svg'),
  icCall('${AppConstants.iconDefault}ic_call.svg'),
  icLocation('${AppConstants.iconDefault}ic_location.svg'),
  icCut('${AppConstants.iconDefault}ic_cut.svg'),
  icMore('${AppConstants.iconDefault}ic_more.svg'),
  icShare('${AppConstants.iconDefault}ic_share.svg'),
  icCancelBooking('${AppConstants.iconDefault}ic_cancel_booking.svg'),
  icCheckBox('${AppConstants.iconDefault}ic_check_box.svg'),
  icDashBox('${AppConstants.iconDefault}ic_dash_box.svg'),
  icCancellationPolicy('${AppConstants.iconDefault}ic_cancellation_policy.svg'),
  icRightArrow('${AppConstants.iconDefault}ic_right_arrow.svg'),
  icAbout('${AppConstants.iconDefault}ic_about.svg'),
  icDelete('${AppConstants.iconDefault}ic_delete.svg'),
  icFaq('${AppConstants.iconDefault}ic_faq.svg'),
  icFriend('${AppConstants.iconDefault}ic_friend.svg'),
  icHelp('${AppConstants.iconDefault}ic_help.svg'),
  icLogout('${AppConstants.iconDefault}ic_logout.svg'),
  icPrivacy('${AppConstants.iconDefault}ic_privacy.svg'),
  icSetting('${AppConstants.iconDefault}ic_setting.svg'),
  icFriendMore('${AppConstants.iconDefault}ic_friend_more.svg'),
  icDownwardArrow('${AppConstants.iconDefault}ic_downward_arrow.svg'),
  icUpwardArrow('${AppConstants.iconDefault}ic_upward_arrow.svg'),
  icPerson('${AppConstants.iconDefault}ic_person.svg'),
  icRedCross('${AppConstants.iconDefault}ic_red_cross.svg'),
  icRedRightArrow('${AppConstants.iconDefault}ic_red_right_arrow.svg'),
  icLocation2('${AppConstants.iconDefault}ic_location2.svg'),
  icAlignArrow('${AppConstants.iconDefault}ic_align_arrow.svg'),
  icGraph('${AppConstants.iconDefault}ic_graph.svg'),
  icSk('${AppConstants.iconDefault}ic_sk.svg'),
  icAdd('${AppConstants.iconDefault}ic_add.svg'),
  icDateOfBirth('${AppConstants.iconDefault}ic_date_of_birth.svg'),
  icEmail('${AppConstants.iconDefault}ic_email.svg'),
  icSelectGender('${AppConstants.iconDefault}ic_select_gender.svg'),
  icEditProfile('${AppConstants.iconDefault}ic_edit_profile.svg'),
  icLeft('${AppConstants.iconDefault}ic_left.svg'),
  icRight('${AppConstants.iconDefault}ic_right.svg'),
  icHeart('${AppConstants.iconDefault}ic_heart.svg'),
  icHeartFilled('${AppConstants.iconDefault}ic_filled_heart.svg'),
  icInfo('${AppConstants.iconDefault}ic_info.svg'),
  icCaddie('${AppConstants.iconDefault}ic_caddie.svg'),
  icCart('${AppConstants.iconDefault}ic_cart.svg'),
  icLocker('${AppConstants.iconDefault}ic_locker.svg'),
  icParking('${AppConstants.iconDefault}ic_parking.svg'),
  icProShop('${AppConstants.iconDefault}ic_pro_shop.svg'),
  icRestaurant('${AppConstants.iconDefault}ic_restaurant.svg'),
  icAddPlayers('${AppConstants.iconDefault}ic_add_players.svg'),
  icRemovedPlayers('${AppConstants.iconDefault}ic_removed_player.svg'),
  icTick('${AppConstants.iconDefault}ic_tick.svg'),
  icSelected('${AppConstants.iconDefault}ic_selected.svg'),
  icAddHcp('${AppConstants.iconDefault}ic_add_hcp.svg'),
  icMinusHcp('${AppConstants.iconDefault}ic_minus_hcp.svg'),
  icBluePerson('${AppConstants.iconDefault}ic_blue_person.svg'),
  icFood('${AppConstants.iconDefault}ic_food.svg'),
  icGolfMap('${AppConstants.iconDefault}ic_golf_map.svg'),
  icMinus('${AppConstants.iconDefault}ic_minus.svg'),
  icMobile('${AppConstants.iconDefault}ic_mobile.svg'),
  icRedEmail('${AppConstants.iconDefault}ic_red_email.svg'),
  icPhone('${AppConstants.iconDefault}ic_phone.svg'),
  icFailure('${AppConstants.iconDefault}ic_failure.svg'),
  icSkorekardLogo('${AppConstants.iconDefault}ic_skorekard_logo.svg'),
  icSuccess('${AppConstants.iconDefault}ic_success.svg'),
  icDelhiGolfClub('${AppConstants.iconDefault}ic_delhi_golf_club.svg'),
  icMemberLogo('${AppConstants.iconDefault}ic_member_logo.svg'),
  icMagnifier('${AppConstants.iconDefault}ic_magnifier.svg'),
  icTeeBooked('${AppConstants.iconDefault}ic_tee_booked.svg'),
  icClosedMenu('${AppConstants.iconDefault}ic_closed_menu.svg'),
  icCopy('${AppConstants.iconDefault}ic_copy.svg'),
  icCity('${AppConstants.iconDefault}ic_city.svg'),
  icCountry('${AppConstants.iconDefault}ic_country.svg'),
  icGallery('${AppConstants.iconDefault}ic_gallery.svg'),
  icCamera('${AppConstants.iconDefault}ic_camera.svg'),
  icAddFriends('${AppConstants.iconDefault}ic_add_friends.svg'),
  icCancelRequest('${AppConstants.iconDefault}ic_cancel_request.svg'),
  icUnfriends('${AppConstants.iconDefault}ic_unfriends.svg'),
  icNoSearchView('${AppConstants.iconDefault}ic_no_search_view.svg'),
  icNoFriendsView('${AppConstants.iconDefault}ic_no_friend_view.svg'),
  icChampion('${AppConstants.iconDefault}ic_champion.svg'),
  icInfoMore('${AppConstants.iconDefault}ic_info_more.svg'),
  icDownArrow('${AppConstants.iconDefault}ic_down_arrow.svg');

  final String path;

  const AppIconsPaths(this.path);
}

enum AppImagePaths {
  imDelhiGolfClub('${AppConstants.imageDefault}delhi_golf_club.jpg'),
  imGoldenGreen('${AppConstants.imageDefault}golden_green.jpg'),
  imKalhaar('${AppConstants.imageDefault}kalhaar.jpg'),
  imImage('${AppConstants.imageDefault}image.jpg'),
  imDLFGolf('${AppConstants.imageDefault}dlf_golf.jpg'),
  imProfileBanner('${AppConstants.imageDefault}profile_banner.jpg'),
  imWalkthroughPage1('${AppConstants.imageDefault}im_walkthrough_page1.jpg'),
  imWalkthroughPage2('${AppConstants.imageDefault}im_walkthrough_page2.jpg'),
  imWalkthroughPage3('${AppConstants.imageDefault}im_walkthrough_page3.jpg'),
  imSkoreKardLogo('${AppConstants.imageDefault}im_skorekard_logo.jpg'),
  imGolfCourtDetailsScreenBanner('${AppConstants.imageDefault}im_golf_court_banner.jpg'),
  imPlaceholder('https://skorekard.webdevprojects.cloud/assets/images/logo-small-320.svg');

  final String path;

  const AppImagePaths(this.path);
}